Update create-vps.yml

diff --git a/.github/workflows/create-vps.yml b/.github/workflows/create-vps.yml
--- a/.github/workflows/create-vps.yml
+++ b/.github/workflows/create-vps.yml
@@ -26,23 +26,23 @@ jobs:
           FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
           FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}
         run: |
-          cat <<EOF > rclone.conf
-[filebase]
-type = s3
-provider = Other
-env_auth = false
-access_key_id = $FILEBASE_ACCESS_KEY
-secret_access_key = $FILEBASE_SECRET_KEY
-endpoint = https://s3.filebase.com
-EOF
+          cat > rclone.conf <<-EOF
+          [filebase]
+          type = s3
+          provider = Other
+          env_auth = false
+          access_key_id = ${FILEBASE_ACCESS_KEY}
+          secret_access_key = ${FILEBASE_SECRET_KEY}
+          endpoint = https://s3.filebase.com
+          EOF
 
           echo "🔁 Checking for backup..."
-          rclone --config rclone.conf copy filebase:$FILEBASE_BUCKET/autovps.zip . || echo "❌ No backup found"
+          rclone --config rclone.conf copy filebase:${FILEBASE_BUCKET}/autovps.zip . || echo "❌ No backup found"
           unzip -o autovps.zip || echo "❌ Failed to unzip or not found"
 
       - name: 🔐 Start tmate SSH Session
         run: |
-          sudo apt install -y tmate
+          sudo apt update && sudo apt install -y tmate
           tmate -S /tmp/tmate.sock new-session -d
           tmate -S /tmp/tmate.sock wait tmate-ready
           SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
@@ -61,18 +61,18 @@ EOF
           FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
           FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}
         run: |
-          cat <<EOF > rclone.conf
-[filebase]
-type = s3
-provider = Other
-env_auth = false
-access_key_id = $FILEBASE_ACCESS_KEY
-secret_access_key = $FILEBASE_SECRET_KEY
-endpoint = https://s3.filebase.com
-EOF
+          cat > rclone.conf <<-EOF
+          [filebase]
+          type = s3
+          provider = Other
+          env_auth = false
+          access_key_id = ${FILEBASE_ACCESS_KEY}
+          secret_access_key = ${FILEBASE_SECRET_KEY}
+          endpoint = https://s3.filebase.com
+          EOF
 
           zip -r autovps.zip . -x ".git/*" ".github/*" "links/*" || echo "❌ Nothing to zip"
-          rclone --config rclone.conf copy autovps.zip filebase:$FILEBASE_BUCKET || echo "❌ Upload failed"
+          rclone --config rclone.conf copy autovps.zip filebase:${FILEBASE_BUCKET} || echo "❌ Upload failed"
 
       - name: ⏳ Keep VPS alive
         run: |
